### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.compute.compute.v2016_04_30_preview.models.inner_error.InnerError
  fullName: azure.mgmt.compute.compute.v2016_04_30_preview.models.inner_error
  langs:
  - python
  module: azure.mgmt.compute.compute.v2016_04_30_preview.models.inner_error
  name: inner_error
  source:
    id: inner_error
    path: azure-mgmt-compute\azure\mgmt\compute\compute\v2016_04_30_preview\models\inner_error.py
    remote:
      branch: master
      path: azure-mgmt-compute\azure\mgmt\compute\compute\v2016_04_30_preview\models\inner_error.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.compute.compute.v2016_04_30_preview.models.inner_error
references:
- fullName: azure.mgmt.compute.compute.v2016_04_30_preview.models.inner_error.InnerError
  isExternal: false
  name: InnerError
  parent: azure.mgmt.compute.compute.v2016_04_30_preview.models.inner_error
  uid: azure.mgmt.compute.compute.v2016_04_30_preview.models.inner_error.InnerError
