### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.compute.compute.v2015_06_15.models.api_error.ApiError
  fullName: azure.mgmt.compute.compute.v2015_06_15.models.api_error
  langs:
  - python
  module: azure.mgmt.compute.compute.v2015_06_15.models.api_error
  name: api_error
  source:
    id: api_error
    path: azure-mgmt-compute\azure\mgmt\compute\compute\v2015_06_15\models\api_error.py
    remote:
      branch: master
      path: azure-mgmt-compute\azure\mgmt\compute\compute\v2015_06_15\models\api_error.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.compute.compute.v2015_06_15.models.api_error
references:
- fullName: azure.mgmt.compute.compute.v2015_06_15.models.api_error.ApiError
  isExternal: false
  name: ApiError
  parent: azure.mgmt.compute.compute.v2015_06_15.models.api_error
  uid: azure.mgmt.compute.compute.v2015_06_15.models.api_error.ApiError
