### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.iothub.models.error_details.ErrorDetails
  - azure.mgmt.iothub.models.error_details.ErrorDetailsException
  fullName: azure.mgmt.iothub.models.error_details
  langs:
  - python
  module: azure.mgmt.iothub.models.error_details
  name: error_details
  source:
    id: error_details
    path: azure-mgmt-iothub\azure\mgmt\iothub\models\error_details.py
    remote:
      branch: master
      path: azure-mgmt-iothub\azure\mgmt\iothub\models\error_details.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.iothub.models.error_details
references:
- fullName: azure.mgmt.iothub.models.error_details.ErrorDetails
  isExternal: false
  name: ErrorDetails
  parent: azure.mgmt.iothub.models.error_details
  uid: azure.mgmt.iothub.models.error_details.ErrorDetails
- fullName: azure.mgmt.iothub.models.error_details.ErrorDetailsException
  isExternal: false
  name: ErrorDetailsException
  parent: azure.mgmt.iothub.models.error_details
  uid: azure.mgmt.iothub.models.error_details.ErrorDetailsException
